"""init schema

Revision ID: 75203f7e12b0
Revises: 
Create Date: 2025-08-11 23:04:40.124234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75203f7e12b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateways',
    sa.Column('node_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=8), server_default='US', nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('heard_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('gateway_node_id', sa.BigInteger(), nullable=False),
    sa.Column('last_heard_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'gateway_node_id', name='uq_heard_map_pair')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('msg_id', sa.String(length=64), nullable=True),
    sa.Column('from_id', sa.String(length=32), nullable=True),
    sa.Column('to_id', sa.String(length=32), nullable=True),
    sa.Column('gateway_node_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direction', 'msg_id', name='uq_direction_msg_id')
    )
    op.create_table('users',
    sa.Column('tg_user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('language', sa.String(length=2), server_default='en', nullable=False),
    sa.Column('tg_code', sa.String(length=8), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('tg_user_id'),
    sa.UniqueConstraint('tg_code')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.Column('owner_tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_gateway_node_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_tg_user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    op.drop_table('users')
    op.drop_table('messages')
    op.drop_table('heard_map')
    op.drop_table('gateways')
    # ### end Alembic commands ###
