"""nodes alias+position

Revision ID: 951b9daf128a
Revises: 75203f7e12b0
Create Date: 2025-08-11 23:49:06.120978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '951b9daf128a'
down_revision: Union[str, None] = '75203f7e12b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('last_lat', sa.DOUBLE_PRECISION(), nullable=True))
    op.add_column('nodes', sa.Column('last_lon', sa.DOUBLE_PRECISION(), nullable=True))
    op.add_column('nodes', sa.Column('last_alt', sa.DOUBLE_PRECISION(), nullable=True))
    op.add_column('nodes', sa.Column('last_position_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # add tg_chat_id to users
    op.add_column('users', sa.Column('tg_chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_chat_id')
    op.drop_column('nodes', 'last_position_at')
    op.drop_column('nodes', 'last_alt')
    op.drop_column('nodes', 'last_lon')
    op.drop_column('nodes', 'last_lat')
    # ### end Alembic commands ###
