"""Add user_label to Node model

Revision ID: be5f569b9fcf
Revises: 951b9daf128a
Create Date: 2025-08-14 02:59:47.689233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5f569b9fcf'
down_revision: Union[str, None] = '951b9daf128a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('user_label', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'user_label')
    # ### end Alembic commands ###
